spring:
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  application.name: Bartender

okta:
  oauth2:
    issuer: https://dev-j5u28jpjlghkvp85.us.auth0.com/
    client-id: WNFPVNOE6er37uvjGPimPExUZ1BSoLFX
